-- MySQL Script generated by MySQL Workbench
-- Sa 09 Mai 2015 20:58:33 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema virtapi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `virtapi` ;

-- -----------------------------------------------------
-- Schema virtapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virtapi` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `virtapi` ;

-- -----------------------------------------------------
-- Table `virtapi`.`cache_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`cache_option` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`cache_option` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cache_type` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `cache_type_UNIQUE` ON `virtapi`.`cache_option` (`cache_type` ASC);

CREATE UNIQUE INDEX `description_UNIQUE` ON `virtapi`.`cache_option` (`description` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`node_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`node_state` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`node_state` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `state_name_UNIQUE` ON `virtapi`.`node_state` (`state_name` ASC);

CREATE UNIQUE INDEX `description_UNIQUE` ON `virtapi`.`node_state` (`description` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`node` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`node` (
  `ipv4_addr_ext` BINARY(4) NOT NULL,
  `ipv6_addr_ext` BINARY(16) NOT NULL,
  `ipv4_gw_ext` BINARY(4) NOT NULL,
  `ipv6_gw_ext` BINARY(16) NOT NULL,
  `bond_interfaces` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `fqdn` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `location` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `state_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_node_1`
    FOREIGN KEY (`state_id`)
    REFERENCES `virtapi`.`node_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `ipv4_addr_ext` ON `virtapi`.`node` (`ipv4_addr_ext` ASC, `ipv6_addr_ext` ASC);

CREATE INDEX `fk_state_id_node` ON `virtapi`.`node` (`state_id` ASC);

CREATE UNIQUE INDEX `ipv4_addr_ext_UNIQUE` ON `virtapi`.`node` (`ipv4_addr_ext` ASC);

CREATE UNIQUE INDEX `ipv6_addr_ext_UNIQUE` ON `virtapi`.`node` (`ipv6_addr_ext` ASC);

CREATE UNIQUE INDEX `FQDN_UNIQUE` ON `virtapi`.`node` (`fqdn` ASC);

CREATE UNIQUE INDEX `location_UNIQUE` ON `virtapi`.`node` (`location` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`vm_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`vm_state` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`vm_state` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `description_UNIQUE` ON `virtapi`.`vm_state` (`description` ASC);

CREATE UNIQUE INDEX `state_name_UNIQUE` ON `virtapi`.`vm_state` (`state_name` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`virt_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`virt_node` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`virt_node` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `node_id` INT NOT NULL,
  `local_storage_gb` INT NULL,
  `vg_name` VARCHAR(45) NULL,
  `local_storage_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vm_node_1`
    FOREIGN KEY (`node_id`)
    REFERENCES `virtapi`.`node` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `node_id_UNIQUE` ON `virtapi`.`virt_node` (`node_id` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`virt_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`virt_method` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`virt_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `virtapi`.`virt_method` (`name` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`node_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`node_method` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`node_method` (
  `hypervisor_id` INT NOT NULL AUTO_INCREMENT,
  `node_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vm_hypervisor_1`
    FOREIGN KEY (`node_id`)
    REFERENCES `virtapi`.`virt_node` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vm_hypervisor_2`
    FOREIGN KEY (`hypervisor_id`)
    REFERENCES `virtapi`.`virt_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_node_id_vm_hypervisor` ON `virtapi`.`node_method` (`node_id` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`vm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`vm` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`vm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cores` INT NOT NULL,
  `ram` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `cputime_limit` INT NULL,
  `state_id` INT NOT NULL,
  `virt_method` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vm_2`
    FOREIGN KEY (`state_id`)
    REFERENCES `virtapi`.`vm_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vm_1`
    FOREIGN KEY (`virt_method`)
    REFERENCES `virtapi`.`node_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `fk_state_id_vm` ON `virtapi`.`vm` (`state_id` ASC);

CREATE INDEX `fk_vm_hypervisor_id_vm` ON `virtapi`.`vm` (`virt_method` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`storage_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`storage_type` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`storage_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `storage_type` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `storage_type_UNIQUE` ON `virtapi`.`storage_type` (`storage_type` ASC);

CREATE UNIQUE INDEX `description_UNIQUE` ON `virtapi`.`storage_type` (`description` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`storage` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`storage` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `storage_type_id` INT(11) NOT NULL,
  `cache_option_id` INT(11) NOT NULL,
  `size` INT(11) NOT NULL,
  `vm_id` INT NULL,
  `write_iops_limit` INT NULL,
  `read_iops_limit` INT NULL,
  `write_mbps_limit` INT NULL,
  `read_mbps_limit` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_storage_vm`
    FOREIGN KEY (`vm_id`)
    REFERENCES `virtapi`.`vm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storage_cache_option`
    FOREIGN KEY (`cache_option_id`)
    REFERENCES `virtapi`.`cache_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storage_storage_type`
    FOREIGN KEY (`storage_type_id`)
    REFERENCES `virtapi`.`storage_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `fk_vm_id` ON `virtapi`.`storage` (`vm_id` ASC);

CREATE INDEX `fk_cache_option_id_storage` ON `virtapi`.`storage` (`cache_option_id` ASC);

CREATE INDEX `fk_storage_type_id_storage` ON `virtapi`.`storage` (`storage_type_id` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`vm_interface`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`vm_interface` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`vm_interface` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vm_id` INT NOT NULL,
  `mac` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vm_interface_1`
    FOREIGN KEY (`vm_id`)
    REFERENCES `virtapi`.`vm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vm_id_vm_interface` ON `virtapi`.`vm_interface` (`vm_id` ASC);

CREATE UNIQUE INDEX `mac_UNIQUE` ON `virtapi`.`vm_interface` (`mac` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`ipv4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`ipv4` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`ipv4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` BINARY(4) NOT NULL,
  `vm_interface_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ipv4_1`
    FOREIGN KEY (`vm_interface_id`)
    REFERENCES `virtapi`.`vm_interface` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vm_interface_id_ipv4` ON `virtapi`.`ipv4` (`vm_interface_id` ASC);

CREATE UNIQUE INDEX `ip_UNIQUE` ON `virtapi`.`ipv4` (`ip` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`ipv6`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`ipv6` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`ipv6` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` BINARY(16) NOT NULL,
  `vm_interface_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ipv6_1`
    FOREIGN KEY (`vm_interface_id`)
    REFERENCES `virtapi`.`vm_interface` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vm_interface_id_ipv4` ON `virtapi`.`ipv6` (`vm_interface_id` ASC);

CREATE UNIQUE INDEX `ip_UNIQUE` ON `virtapi`.`ipv6` (`ip` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`ceph_pool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`ceph_pool` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`ceph_pool` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `virtapi`.`ceph_pool` (`name` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`storage_ceph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`storage_ceph` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`storage_ceph` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `storage_id` INT NOT NULL,
  `discard` TINYINT(1) NOT NULL DEFAULT 1,
  `pool_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_storage_ceph_1`
    FOREIGN KEY (`pool_id`)
    REFERENCES `virtapi`.`ceph_pool` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `storage_id_UNIQUE` ON `virtapi`.`storage_ceph` (`storage_id` ASC);

CREATE INDEX `fk_pool_id_storage_ceph` ON `virtapi`.`storage_ceph` (`pool_id` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`vlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`vlan` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`vlan` (
  `vm_interface_id` INT NOT NULL AUTO_INCREMENT,
  `id` INT NOT NULL,
  `tag` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vlan_1`
    FOREIGN KEY (`vm_interface_id`)
    REFERENCES `virtapi`.`vm_interface` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vm_interface_id_vlan` ON `virtapi`.`vlan` (`vm_interface_id` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`ceph_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`ceph_node` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`ceph_node` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `port` INT NOT NULL,
  `node_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ceph_node_1`
    FOREIGN KEY (`node_id`)
    REFERENCES `virtapi`.`node` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `node_id_UNIQUE` ON `virtapi`.`ceph_node` (`node_id` ASC);


-- -----------------------------------------------------
-- Table `virtapi`.`mon_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtapi`.`mon_node` ;

CREATE TABLE IF NOT EXISTS `virtapi`.`mon_node` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `port` INT NOT NULL,
  `node_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_mon_node_1`
    FOREIGN KEY (`node_id`)
    REFERENCES `virtapi`.`node` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mon_node_1_idx` ON `virtapi`.`mon_node` (`node_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
